//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.29 at 02:30:04 PM GMT+04:00 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://soap.usermanagementapp.codemark.ru", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.codemark.usermanagementapp.soap;
